#!/bin/bash

# Auto-Build Environment Setup
# Smart Heating Manual Override Feature
# Generated by Planner Agent - 2025-12-23

set -e

echo "========================================"
echo "Smart Heating Override Feature"
echo "Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ============================================
# PROJECT INFORMATION
# ============================================

echo -e "${BLUE}Project Type:${NC} Home Assistant Blueprint"
echo -e "${BLUE}Target File:${NC} smart_heating/smart_heating.yaml"
echo -e "${BLUE}Feature:${NC} Manual Override with 1-Hour Duration"
echo ""

# ============================================
# VALIDATION
# ============================================

echo -e "${YELLOW}Validating YAML syntax...${NC}"
if python3 -c "import yaml; yaml.safe_load(open('smart_heating/smart_heating.yaml'))" 2>/dev/null; then
    echo -e "${GREEN}✓ YAML syntax valid${NC}"
else
    echo -e "${RED}✗ YAML syntax error${NC}"
    exit 1
fi

# Check Python is available
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found${NC}"
    exit 1
fi

# ============================================
# ENVIRONMENT INFO
# ============================================

echo ""
echo -e "${BLUE}Home Assistant Integration Info:${NC}"
echo "- Blueprint Version: 1.2.4"
echo "- Min Home Assistant Version: 2025.12.0"
echo "- Domain: automation"
echo ""

# ============================================
# SETUP INSTRUCTIONS
# ============================================

echo -e "${BLUE}To test this blueprint:${NC}"
echo ""
echo "1. In Home Assistant Settings → Automations & Scenes → Blueprints"
echo "2. Click 'Import Blueprint'"
echo "3. Choose 'Repository' and enter:"
echo "   https://github.com/r3mcos3/blueprints/blob/main/smart_heating/smart_heating.yaml"
echo ""
echo "4. Click 'Preview' then 'Import'"
echo "5. Create a new automation from the blueprint"
echo "6. Configure required inputs:"
echo "   - Climate Entity (e.g., climate.tado)"
echo "   - Indoor Temperature Sensor"
echo "   - Outdoor Temperature Sensor"
echo "   - Presence Zone (zone.home)"
echo "   - Door/Window Sensors"
echo ""
echo "7. Enable Manual Override Settings section"
echo "8. Create helper entities:"
echo "   - input_datetime for override timestamp"
echo "   - input_number for override temperature (optional)"
echo ""

# ============================================
# TESTING QUICK REFERENCE
# ============================================

echo -e "${BLUE}Testing Checklist:${NC}"
echo "□ YAML syntax valid (checked above)"
echo "□ Blueprint imports without errors"
echo "□ Override input variables visible in UI"
echo "□ Override activation triggers temperature change"
echo "□ Override expires after 1 hour"
echo "□ Automation resumes normal control after expiration"
echo "□ Frost protection still enforces minimum temperature"
echo "□ All existing modes work with override inactive"
echo ""

# ============================================
# IMPLEMENTATION PHASES
# ============================================

echo -e "${BLUE}Implementation Phases:${NC}"
echo ""
echo "Phase 1: Core Override Implementation"
echo "  Subtask 1-1: Add override input variables"
echo "  Subtask 1-2: Add override trigger IDs"
echo "  Subtask 1-3: Add override state variables"
echo "  Subtask 1-4: Insert override mode check"
echo "  Subtask 1-5: Add override temperature logic"
echo "  Subtask 1-6: Add override action handler"
echo ""
echo "Phase 2: Documentation Update"
echo "  Subtask 2-1: Update README with override docs"
echo ""

# ============================================
# READY
# ============================================

echo -e "${GREEN}✓ Environment setup complete${NC}"
echo ""
echo "Next steps:"
echo "  1. Review implementation_plan.json for detailed subtasks"
echo "  2. Read context.json for pattern analysis"
echo "  3. Start implementation with subtask-1-1"
echo ""
echo "Documentation: smart_heating/README.md"
echo "Blueprint File: smart_heating/smart_heating.yaml"
echo ""

# ============================================
# SUMMARY
# ============================================

echo "========================================"
echo "Ready to implement!"
echo "========================================"
echo ""
echo "Run this command to continue:"
echo "  source auto-claude/.venv/bin/activate && python auto-claude/run.py --spec 002 --parallel 1"
echo ""
