# Version: 1.1.0
blueprint:
  domain: automation
  name: "ðŸ”‹ Accu Saver - Battery Health Manager"
  author: r3mcos3
  source_url: https://github.com/r3mcos3/blueprints/blob/main/accu_saver/accu_saver.yaml
  homeassistant:
    min_version: 2025.12.0
  description: >
    ðŸ“¦ [Version 1.1.0] Smart battery health management for laptop servers!
    Automatically controls charging via smart plug to maintain optimal battery levels
    and extend battery lifespan. ðŸ”Œâš¡


    Features:

    - ðŸ”‹ Battery level monitoring with dual thresholds

    - âš¡ Automatic charge control via smart plug

    - ðŸŽ¯ Configurable upper/lower battery limits

    - ðŸ”„ Immediate response - no delays

    - â° Periodic status checks for automatic synchronization

    - ðŸ›¡ï¸ Prevents overcharging and deep discharge

    - ðŸš€ Startup synchronization for correct initial state

  input:
    # ===== REQUIRED: BATTERY SENSOR =====
    battery_sensor:
      name: "ðŸ”‹ Battery Percentage Sensor"
      description: >
        The sensor that monitors battery level percentage (e.g., sensor.laptop_battery_level).
        Must report values between 0-100.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: battery

    # ===== REQUIRED: SMART PLUG CONTROL =====
    smart_plug:
      name: "ðŸ”Œ Smart Plug/Switch"
      description: >
        The smart plug or switch controlling the charger.
        Turning OFF stops charging, turning ON resumes charging.
      selector:
        entity:
          filter:
            - domain: switch

    # ===== BATTERY THRESHOLD SETTINGS =====
    battery_thresholds:
      name: "ðŸŽ¯ Battery Threshold Settings"
      icon: mdi:battery-charging
      collapsed: true
      input:
        upper_threshold:
          name: "â¬†ï¸ Upper Threshold (Stop Charging)"
          description: >
            When battery reaches this percentage, charging will stop.
            Recommended: 80% for optimal battery health.
          default: 80
          selector:
            number:
              min: 50
              max: 100
              step: 5
              unit_of_measurement: "%"
              mode: slider

        lower_threshold:
          name: "â¬‡ï¸ Lower Threshold (Start Charging)"
          description: >
            When battery drops to this percentage, charging will resume.
            Recommended: 20% to avoid deep discharge.
          default: 20
          selector:
            number:
              min: 5
              max: 50
              step: 5
              unit_of_measurement: "%"
              mode: slider

        check_interval:
          name: "â° Periodic Check Interval"
          description: >
            How often to check and sync battery/plug state (in minutes).
            Helps maintain correct state even after manual overrides.
            Set to 0 to disable periodic checks.
          default: 30
          selector:
            number:
              min: 0
              max: 120
              step: 5
              unit_of_measurement: "min"
              mode: slider

mode: single
max_exceeded: silent

variables:
  # Input references
  battery: !input battery_sensor
  plug: !input smart_plug
  upper_limit: !input upper_threshold
  lower_limit: !input lower_threshold
  check_interval: !input check_interval

  # Current state calculations
  current_battery_level: "{{ states(battery) | float(0) }}"
  plug_is_on: "{{ is_state(plug, 'on') }}"
  battery_sensor_available: "{{ not is_state(battery, 'unavailable') and not is_state(battery, 'unknown') }}"

triggers:
  # ===== BATTERY LEVEL TRIGGERS =====
  - trigger: numeric_state
    entity_id: !input battery_sensor
    above: !input upper_threshold
    id: battery_high

  - trigger: numeric_state
    entity_id: !input battery_sensor
    below: !input lower_threshold
    id: battery_low

  # ===== STARTUP TRIGGERS =====
  - trigger: homeassistant
    event: start
    id: ha_start

  - trigger: event
    event_type: automation_reloaded
    id: automation_reload

  # ===== SENSOR RECOVERY TRIGGER =====
  - trigger: state
    entity_id: !input battery_sensor
    from:
      - "unavailable"
      - "unknown"
    id: sensor_recovered

  # ===== PERIODIC CHECK TRIGGER =====
  - trigger: time_pattern
    minutes: "/1"
    id: periodic_check

conditions: []

actions:
  # ===== BATTERY HIGH - STOP CHARGING =====
  - choose:
      - conditions:
          - condition: trigger
            id: battery_high
          - condition: template
            value_template: "{{ battery_sensor_available }}"
          - condition: template
            value_template: "{{ plug_is_on }}"
        sequence:
          - action: switch.turn_off
            target:
              entity_id: "{{ plug }}"

      # ===== BATTERY LOW - START CHARGING =====
      - conditions:
          - condition: trigger
            id: battery_low
          - condition: template
            value_template: "{{ battery_sensor_available }}"
          - condition: template
            value_template: "{{ not plug_is_on }}"
        sequence:
          - action: switch.turn_on
            target:
              entity_id: "{{ plug }}"

      # ===== SENSOR RECOVERED - SYNC STATE =====
      - conditions:
          - condition: trigger
            id: sensor_recovered
          - condition: template
            value_template: "{{ battery_sensor_available }}"
        sequence:
          - choose:
              # Battery is high, ensure plug is OFF
              - conditions:
                  - condition: template
                    value_template: "{{ current_battery_level >= upper_limit }}"
                  - condition: template
                    value_template: "{{ plug_is_on }}"
                sequence:
                  - action: switch.turn_off
                    target:
                      entity_id: "{{ plug }}"

              # Battery is low, ensure plug is ON
              - conditions:
                  - condition: template
                    value_template: "{{ current_battery_level <= lower_limit }}"
                  - condition: template
                    value_template: "{{ not plug_is_on }}"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: "{{ plug }}"

      # ===== STARTUP/RELOAD - INITIALIZE STATE =====
      - conditions:
          - condition: trigger
            id:
              - ha_start
              - automation_reload
          - condition: template
            value_template: "{{ battery_sensor_available }}"
        sequence:
          - delay:
              seconds: 10
          - choose:
              # Battery above upper threshold - ensure charging is OFF
              - conditions:
                  - condition: template
                    value_template: "{{ current_battery_level >= upper_limit }}"
                  - condition: template
                    value_template: "{{ plug_is_on }}"
                sequence:
                  - action: switch.turn_off
                    target:
                      entity_id: "{{ plug }}"

              # Battery below lower threshold - ensure charging is ON
              - conditions:
                  - condition: template
                    value_template: "{{ current_battery_level <= lower_limit }}"
                  - condition: template
                    value_template: "{{ not plug_is_on }}"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: "{{ plug }}"

      # ===== PERIODIC CHECK - SYNC STATE =====
      - conditions:
          - condition: trigger
            id: periodic_check
          - condition: template
            value_template: "{{ check_interval > 0 }}"
          - condition: template
            value_template: "{{ now().minute % check_interval == 0 }}"
          - condition: template
            value_template: "{{ battery_sensor_available }}"
        sequence:
          - choose:
              # Battery above upper threshold - ensure charging is OFF
              - conditions:
                  - condition: template
                    value_template: "{{ current_battery_level >= upper_limit }}"
                  - condition: template
                    value_template: "{{ plug_is_on }}"
                sequence:
                  - action: switch.turn_off
                    target:
                      entity_id: "{{ plug }}"

              # Battery below lower threshold - ensure charging is ON
              - conditions:
                  - condition: template
                    value_template: "{{ current_battery_level <= lower_limit }}"
                  - condition: template
                    value_template: "{{ not plug_is_on }}"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: "{{ plug }}"
    default: []
