# Version: 1.0.3
blueprint:
  name: "ðŸš— AI - Parking Spot Counter"
  description:
    "ðŸ“¦ [Version 1.0.3] Analyzes camera feed with AI to count free and occupied parking
    spaces upon arrival, updating sensors and sending a notification."
  domain: automation
  source_url: https://github.com/r3mcos3/blueprints/blob/main/ai_parking_counter/ai_parking_counter.yaml

  input:
    person_entity:
      name: ðŸ‘¤ Person
      description: The person entity to track for zone arrivals.
      selector:
        entity:
          domain: person

    zone_1:
      name: ðŸ˜ï¸ Zone 1
      description: First zone to monitor for arrival (e.g., zone.huibevendreef).
      selector:
        entity:
          domain: zone

    zone_2:
      name: ðŸ˜ï¸ Zone 2
      description: Second zone to monitor for arrival (e.g., zone.moerse_dreef).
      selector:
        entity:
          domain: zone

    proximity_sensor:
      name: ðŸ§­ Proximity Direction Sensor
      description: Proximity sensor that indicates direction of travel (should have state "towards" when approaching).
      selector:
        entity:
          domain: sensor

    camera_entity:
      name: ðŸ“· Camera
      description: Camera to analyze for parking spots (must support snapshot and streaming).
      selector:
        entity:
          domain: camera

    ai_task_entity:
      name: ðŸ¤– AI Task Entity
      description: The AI task entity to use for image analysis (e.g., ai_task.google_ai_task).
      selector:
        entity:
          domain: ai_task

    parking_spaces_total:
      name: ðŸ…¿ï¸ Total Parking Spaces
      description: Total number of parking spaces to count (default is 3).
      default: 3
      selector:
        number:
          min: 1
          max: 10
          mode: slider

    free_spots_sensor:
      name: ðŸŸ¢ Free Spots Sensor
      description: Input number entity to store the count of free parking spots.
      selector:
        entity:
          domain: input_number

    occupied_spots_sensor:
      name: ðŸ”´ Occupied Spots Sensor
      description: Input number entity to store the count of occupied parking spots.
      selector:
        entity:
          domain: input_number

    telegram_bot:
      name: ðŸ“± Telegram Bot
      description: >
        Select your Telegram bot. Leave empty to disable notifications.
      default: {}
      selector:
        config_entry:
          integration: telegram_bot

    telegram_message:
      name: ðŸ’¬ Telegram Message
      description: >
        Message to send via Telegram. Use {free_spots} as placeholder for number of free parking spots.
        Only sent when Telegram Bot is selected.
      default: "Er zijn {free_spots} parkeerplaatsen ðŸš— vrij voor de deur! ðŸšª"
      selector:
        text:
          multiline: true

    telegram_title:
      name: ðŸ·ï¸ Telegram Title (Optional)
      description: >
        Optional title for the Telegram notification. Leave empty for no title.
      default: ""
      selector:
        text:

    snapshot_enabled:
      name: ðŸ“¸ Save Snapshot
      description: Save a camera snapshot when analyzing parking spots.
      default: true
      selector:
        boolean:

    snapshot_path:
      name: ðŸ—‚ï¸ Snapshot Path
      description: File path to save the snapshot (e.g., /config/www/parking_spot.jpg).
      default: "/config/www/parking_spot.jpg"
      selector:
        text:

    ai_instructions:
      name: ðŸ“ AI Instructions (Optional)
      description: >
        Custom instructions for the AI to analyze parking spots.
        Leave empty to use default instructions. Use {total_spaces} as placeholder for total spaces.
      default: ""
      selector:
        text:
          multiline: true

mode: single

trigger:
  - platform: zone
    entity_id: !input person_entity
    zone: !input zone_1
    event: enter
    id: zone_1_enter
  - platform: zone
    entity_id: !input person_entity
    zone: !input zone_2
    event: enter
    id: zone_2_enter

condition:
  - condition: state
    entity_id: !input proximity_sensor
    state: towards

action:
  - variables:
      _camera: !input camera_entity
      _ai_task: !input ai_task_entity
      _total_spaces: !input parking_spaces_total
      _free_sensor: !input free_spots_sensor
      _occupied_sensor: !input occupied_spots_sensor
      _telegram_bot: !input telegram_bot
      _telegram_message: !input telegram_message
      _telegram_title: !input telegram_title
      _snapshot_enabled: !input snapshot_enabled
      _snapshot_path: !input snapshot_path
      _custom_instructions: !input ai_instructions
      _default_instructions: >
        Look at this image of the street in front of my house. There are {{ _total_spaces }}
        parking spaces directly in front of the door. Count how many of these {{ _total_spaces }}
        spaces are FREE (no car parked) and how many are OCCUPIED (car parked).
      _final_instructions: >
        {% if _custom_instructions | trim != "" %}
          {{ _custom_instructions | replace('{total_spaces}', _total_spaces | string) }}
        {% else %}
          {{ _default_instructions }}
        {% endif %}

  - alias: Analyse camera with AI
    action: ai_task.generate_data
    data:
      instructions: "{{ _final_instructions }}"
      structure:
        vrije_plekken:
          selector:
            number:
              min: 0
              max: !input parking_spaces_total
        bezette_plekken:
          selector:
            number:
              min: 0
              max: !input parking_spaces_total
      entity_id: "{{ _ai_task }}"
      task_name: Scan Free Park Spaces
      attachments:
        media_content_id: "media-source://camera/{{ _camera }}"
        media_content_type: application/vnd.apple.mpegurl
        metadata:
          title: "{{ state_attr(_camera, 'friendly_name') | default('Camera') }}"
          thumbnail: "/api/camera_proxy/{{ _camera }}"
          media_class: video
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://camera
    response_variable: parking_result
    enabled: true

  - alias: Update free parking spots
    action: input_number.set_value
    target:
      entity_id: "{{ _free_sensor }}"
    data:
      value: "{{ parking_result.data.vrije_plekken | int(0) }}"

  - alias: Update occupied parking spots
    action: input_number.set_value
    target:
      entity_id: "{{ _occupied_sensor }}"
    data:
      value: "{{ parking_result.data.bezette_plekken | int(0) }}"

  - alias: Send Telegram notification
    if:
      - condition: template
        value_template: "{{ _telegram_bot != none and _telegram_message | trim != '' }}"
    then:
      - action: telegram_bot.send_message
        data:
          config_entry_id: "{{ _telegram_bot }}"
          title: >-
            {% if _telegram_title | trim != '' %}
              {{ _telegram_title }}
            {% endif %}
          message: >-
            {{ _telegram_message | replace('{free_spots}', states(_free_sensor)) }}

  - alias: Save camera snapshot
    if:
      - condition: template
        value_template: "{{ _snapshot_enabled | bool }}"
    then:
      - action: camera.snapshot
        target:
          entity_id: "{{ _camera }}"
        data:
          filename: "{{ _snapshot_path }}"
