blueprint:
  domain: automation
  name: ðŸ”ˆï¸ Volume Controle 3.0
  author: r3mcos3
  source_url: https://github.com/r3mcos3/blueprints/blob/main/volumecontrol/volume_control3.yaml
  homeassistant:
    min_version: "2024.3.0"
  description: >
    Blueprint to automate all your speakers ðŸ”ˆï¸
    
    
    ðŸ“¦ï¸ Version: 2.0

  input:
    media:
      name: ðŸ“»ï¸ Media Players
      description: Speakers to use.
      default: []
      selector:
        target:
          entity:
            - domain:
                - media_player
    scheduler:
      name: ðŸ—“ï¸ Scheduler
      description: >
        scheduler to use,

        for more information about schedulers click [here](https://www.home-assistant.io/integrations/schedule/)

        to make your scheduler click [here](https://my.home-assistant.io/redirect/helpers/).
      default: []
      selector:
        entity:
          filter:
            - domain:
                - schedule
    volume_up:
      name: ðŸ”Š Volume Up Level
      description: >
        The volume goes to this level when the scheduler goes to on
      default: 0.6
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    volume_down:
      name: ðŸ”ˆï¸ Volume Down Level
      description: >
        The volume goes to this level when the scheduler goes to off
      default: 0.2
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    custom_action:
      name: ðŸŽ¬ Custom Action
      description: >
        `optional`


        This custom action gets executed if scheduler get to 'on' or 'off'
      default:
      selector:
        action:
mode: single

trigger:
  - platform: state
    entity_id: !input scheduler
    to: "on"
    id: aan
  - platform: state
    entity_id: !input scheduler
    to: "off"
    id: uit
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - aan
        sequence:
          - service: media_player.volume_set
            target: !input media
            data:
              volume_level: !input volume_up
      - conditions:
          - condition: trigger
            id:
              - uit
        sequence:
          - service: media_player.volume_set
            target: !input media
            data:
              volume_level: !input volume_down
  - if:
      - condition: template
        value_template: "{{ input_custom_action != none }}"
    then: !input custom_action