# Version: 1.0
blueprint:
  domain: automation
  name: ðŸ”ˆ Volume Control!
  author: r3mcos3
  source_url: https://github.com/r3mcos3/blueprints/blob/main/volumecontrol/volumecontrol.yaml
  homeassistant:
    min_version: 2025.12.0
  description: >
    ðŸ“¦ [Version 1.0] Blueprint to automate all your speakers ðŸ”ˆ

  input:
    media:
      name: ðŸ“» Media Players
      description: >
        `Speakers`


        Speakers to use.
      default: []
      selector:
        target:
          entity:
            - domain:
                - media_player
    scheduler:
      name: ðŸ—“ï¸ Scheduler
      description: >
        `Scheduler`


        for more information about schedulers click [here](https://www.home-assistant.io/integrations/schedule/)

        to make your scheduler click [here](https://my.home-assistant.io/redirect/helpers/).
      default: []
      selector:
        entity:
          filter:
            - domain:
                - schedule
    volume_up:
      name: ðŸ”Š Volume Up Level
      description: >
        `Volume High Setting`


        The volume goes to this level when the scheduler goes to on
      default: 0.6
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    volume_down:
      name: ðŸ”ˆ Volume Down Level
      description: >
        `Volume Low Setting`


        The volume goes to this level when the scheduler goes to off
      default: 0.2
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    custom_action:
      name: ðŸŽ¬ Custom Action
      description: >
        `Custom Action` `Optional`


        This custom action gets executed if scheduler get to 'on' or 'off'
      default:
      selector:
        action:
mode: single

trigger:
  - platform: state
    entity_id: !input scheduler
    to: "on"
    id: aan
  - platform: state
    entity_id: !input scheduler
    to: "off"
    id: uit
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - aan
        sequence:
          - service: media_player.volume_set
            target: !input media
            data:
              volume_level: !input volume_up
      - conditions:
          - condition: trigger
            id:
              - uit
        sequence:
          - service: media_player.volume_set
            target: !input media
            data:
              volume_level: !input volume_down
  - if:
      - condition: template
        value_template: "{{ input_custom_action != none }}"
    then: !input custom_action
